Table users {
    user_id INTEGER [primary key]
    profile_name TEXT [NOT NULL]
}

table hubs {
    hub_id INTEGER [primary key]
    hub_name TEXT [NOT NULL, UNIQUE]
    hub_domain TEXT [NOT NULL]
}

table hub_memberships {
    user_id INTEGER
    hub_id INTEGER
}

ref: hub_memberships.hub_id > hubs.hub_id
ref: hub_memberships.user_id > users.user_id